import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Navber from "@/components/Navber";
import { ToastContainer } from "react-toastify";
import Providers from "./providers";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Pet Adoption Platform",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-scroll-behavior="smooth"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
       <Providers>
          <Navber />
          {children}
          <Footer />
          </Providers>
          <ToastContainer />
      </body>
    </html>
  );
}
